services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: danilore_mysql
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-danilore_rifas}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-danilore123}
      MYSQL_USER: ${DB_USERNAME:-danilore}
      MYSQL_PASSWORD: ${DB_PASSWORD:-danilore123}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    networks:
      - danilore_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: danilore_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/storage/logs:/var/www/storage/logs
      - ./backend/storage/app:/var/www/storage/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - danilore_network

  # Frontend Vue.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: danilore_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env
    networks:
      - danilore_network

volumes:
  mysql_data:
    driver: local

networks:
  danilore_network:
    driver: bridge
